// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_PostHousesImage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//web-->srv
type Request struct {
	//sessionid
	Sessionid string `protobuf:"bytes,1,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
	//二进制图片
	Image []byte `protobuf:"bytes,2,opt,name=Image,proto3" json:"Image,omitempty"`
	//房屋id
	HouseId string `protobuf:"bytes,3,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	//图片大小
	Filesize int64 `protobuf:"varint,4,opt,name=filesize,proto3" json:"filesize,omitempty"`
	//图片名
	Filename             string   `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionid() string {
	if m != nil {
		return m.Sessionid
	}
	return ""
}

func (m *Request) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Request) GetHouseId() string {
	if m != nil {
		return m.HouseId
	}
	return ""
}

func (m *Request) GetFilesize() int64 {
	if m != nil {
		return m.Filesize
	}
	return 0
}

func (m *Request) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

//srv--web
type Response struct {
	//错误码
	Errno string `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	//错误信息
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	//房屋图片url，不完整，需要拼接
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.PostHousesImage.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.PostHousesImage.Response")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0xf4, 0x30,
	0x14, 0x85, 0xff, 0xfc, 0x75, 0xa6, 0xed, 0x45, 0x50, 0x82, 0x48, 0x1c, 0x67, 0x51, 0x0a, 0x4a,
	0x57, 0x11, 0xf4, 0x19, 0x04, 0xc7, 0x95, 0xe4, 0x05, 0xa4, 0x63, 0xaf, 0x35, 0xd0, 0xf4, 0xd6,
	0xdc, 0x56, 0xc4, 0xa7, 0xf0, 0x91, 0xa5, 0x69, 0x67, 0x04, 0x17, 0xba, 0x4a, 0xbe, 0x93, 0x9c,
	0xe4, 0xdc, 0x03, 0xe7, 0x9d, 0xa7, 0x9e, 0xae, 0xf0, 0xbd, 0x74, 0x5d, 0x83, 0xbb, 0x55, 0x07,
	0x55, 0xae, 0x6b, 0xd2, 0xce, 0x3e, 0x79, 0xd2, 0xec, 0xdf, 0xf4, 0x03, 0x71, 0x7f, 0x47, 0x03,
	0x23, 0x6f, 0x5c, 0x59, 0x63, 0xfe, 0x29, 0x20, 0x36, 0xf8, 0x3a, 0x20, 0xf7, 0x72, 0x0d, 0x29,
	0x23, 0xb3, 0xa5, 0xd6, 0x56, 0x4a, 0x64, 0xa2, 0x48, 0xcd, 0xb7, 0x20, 0x4f, 0x60, 0x11, 0x2c,
	0xea, 0x7f, 0x26, 0x8a, 0x43, 0x33, 0x81, 0x3c, 0x83, 0xe4, 0x65, 0x7c, 0xee, 0xd1, 0x56, 0x2a,
	0x0a, 0x96, 0x38, 0xf0, 0xa6, 0x92, 0x2b, 0x48, 0x9e, 0x6d, 0x83, 0x6c, 0x3f, 0x50, 0x1d, 0x64,
	0xa2, 0x88, 0xcc, 0x9e, 0x77, 0x67, 0x6d, 0xe9, 0x50, 0x2d, 0x82, 0x6d, 0xcf, 0xf9, 0x3d, 0x24,
	0x06, 0xb9, 0xa3, 0x96, 0x71, 0xfc, 0x14, 0xbd, 0x6f, 0x69, 0x8e, 0x33, 0x81, 0x3c, 0x85, 0x25,
	0x7a, 0xef, 0xb8, 0x0e, 0x59, 0x52, 0x33, 0x93, 0x3c, 0x86, 0x68, 0xf0, 0xcd, 0x9c, 0x63, 0xdc,
	0x5e, 0x3b, 0x88, 0x6f, 0xa7, 0x36, 0xe4, 0x16, 0x8e, 0x7e, 0x0c, 0x2f, 0x2f, 0xf4, 0x6f, 0xdd,
	0xe8, 0xb9, 0x97, 0xd5, 0xe5, 0x5f, 0xd7, 0xa6, 0xb0, 0xf9, 0xbf, 0xed, 0x32, 0x54, 0x7e, 0xf3,
	0x15, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x6f, 0x26, 0xb2, 0x91, 0x01, 0x00, 0x00,
}
