// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_PostUserAuth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type Request struct {
	RealName             string   `protobuf:"bytes,1,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdCard               string   `protobuf:"bytes,2,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	Sessionid            string   `protobuf:"bytes,3,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *Request) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *Request) GetSessionid() string {
	if m != nil {
		return m.Sessionid
	}
	return ""
}

type Response struct {
	Errno                string   `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.PostUserAuth.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.PostUserAuth.Response")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4b, 0x04, 0x31,
	0x10, 0x85, 0x3d, 0xc5, 0xdd, 0xdb, 0xc1, 0x6a, 0x10, 0x5d, 0x3d, 0x0b, 0x59, 0x1b, 0xab, 0x08,
	0xda, 0xd8, 0x8a, 0xd8, 0x8a, 0x2c, 0x58, 0x58, 0xc8, 0x11, 0x2f, 0xc3, 0x19, 0xb8, 0x64, 0xd6,
	0x99, 0x9c, 0xf8, 0xf3, 0xc5, 0xe4, 0x16, 0x6d, 0xbc, 0x2a, 0xbc, 0xf7, 0xc2, 0xe3, 0x7d, 0x03,
	0xb3, 0x41, 0x38, 0xf1, 0x15, 0x7d, 0xd9, 0x30, 0xac, 0x68, 0x7c, 0x4d, 0x76, 0xf1, 0x64, 0xc9,
	0x26, 0xf8, 0x85, 0xb0, 0x51, 0xf9, 0x34, 0x4f, 0xac, 0xe9, 0x59, 0x49, 0xee, 0xd6, 0xe9, 0xbd,
	0x7b, 0x85, 0xba, 0xa7, 0x8f, 0x35, 0x69, 0xc2, 0x19, 0x34, 0x42, 0x76, 0x35, 0x8f, 0x36, 0x50,
	0x3b, 0x39, 0x9f, 0x5c, 0x36, 0xfd, 0xf4, 0xc7, 0x78, 0xb4, 0x81, 0xf0, 0x18, 0x6a, 0xef, 0xe6,
	0x0b, 0x2b, 0xae, 0xdd, 0xcd, 0x51, 0xe5, 0xdd, 0xbd, 0x15, 0x87, 0x67, 0xd0, 0x28, 0xa9, 0x7a,
	0x8e, 0xde, 0xb5, 0x7b, 0x39, 0xfa, 0x35, 0xba, 0x5b, 0x98, 0xf6, 0xa4, 0x03, 0x47, 0x25, 0x3c,
	0x84, 0x7d, 0x12, 0x89, 0xbc, 0xe9, 0x2e, 0x02, 0x8f, 0xa0, 0x22, 0x91, 0xa0, 0xcb, 0xb1, 0xb7,
	0xa8, 0x6b, 0x07, 0xf5, 0x43, 0x81, 0xc0, 0x17, 0x38, 0xf8, 0xbb, 0x19, 0x3b, 0xf3, 0x2f, 0x8f,
	0xd9, 0xc0, 0x9c, 0x5e, 0x6c, 0xfd, 0x53, 0x16, 0x75, 0x3b, 0x6f, 0x55, 0x3e, 0xd0, 0xcd, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x62, 0x40, 0x0f, 0x3f, 0x01, 0x00, 0x00,
}
