// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_PostHouses

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//web-->srv
type Request struct {
	//sessionid
	Sessionid string `protobuf:"bytes,1,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
	//从前段接收到的数据
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionid() string {
	if m != nil {
		return m.Sessionid
	}
	return ""
}

func (m *Request) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//srv--web
type Response struct {
	//错误码
	Errno string `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	//错误信息
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	//返回的房屋id
	HouseId              int64    `protobuf:"varint,3,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetHouseId() int64 {
	if m != nil {
		return m.HouseId
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.PostHouses.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.PostHouses.Response")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x3f, 0x4b, 0xc5, 0x40,
	0x10, 0xc4, 0x3d, 0x9f, 0xbe, 0x24, 0x8b, 0xd5, 0x22, 0x1a, 0xff, 0x14, 0x67, 0xaa, 0x54, 0x27,
	0x68, 0x69, 0x2d, 0x68, 0x27, 0x97, 0x5e, 0x89, 0xde, 0x12, 0x0f, 0x4c, 0x36, 0xde, 0x5e, 0xc4,
	0x8f, 0x2f, 0x5e, 0x22, 0xa9, 0x7c, 0xd5, 0xee, 0x0c, 0x3b, 0xf0, 0x9b, 0x85, 0x8b, 0x31, 0x70,
	0xe4, 0x6b, 0xfa, 0x6e, 0xfb, 0xf1, 0x83, 0xfe, 0xa6, 0x49, 0x2e, 0x9e, 0x76, 0x6c, 0x7a, 0xff,
	0x16, 0xd8, 0x48, 0xf8, 0x32, 0x4f, 0x2c, 0xf1, 0x81, 0x27, 0x21, 0xa9, 0xee, 0x20, 0xb3, 0xf4,
	0x39, 0x91, 0x44, 0xbc, 0x84, 0x42, 0x48, 0xc4, 0xf3, 0xe0, 0x5d, 0xa9, 0xb4, 0xaa, 0x0b, 0xbb,
	0x1a, 0x88, 0x70, 0xe0, 0xda, 0xd8, 0x96, 0xfb, 0x5a, 0xd5, 0x47, 0x36, 0xed, 0x55, 0x03, 0xb9,
	0x25, 0x19, 0x79, 0x10, 0xc2, 0x63, 0x38, 0xa4, 0x10, 0x06, 0x5e, 0x92, 0xb3, 0xc0, 0x13, 0xd8,
	0x52, 0x08, 0xbd, 0x74, 0x29, 0x57, 0xd8, 0x45, 0xe1, 0x19, 0xe4, 0xef, 0xbf, 0x00, 0x2f, 0xde,
	0x95, 0x1b, 0xad, 0xea, 0x8d, 0xcd, 0x92, 0x7e, 0x74, 0x37, 0xcf, 0x90, 0xdd, 0xcf, 0xec, 0xd8,
	0x00, 0xac, 0xa8, 0xa8, 0xcd, 0x3f, 0x25, 0xcc, 0xd2, 0xe0, 0xfc, 0x6a, 0xc7, 0xc5, 0x8c, 0x59,
	0xed, 0xbd, 0x6e, 0xd3, 0x47, 0x6e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x74, 0xed, 0x8f, 0x20,
	0x30, 0x01, 0x00, 0x00,
}
