// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_PutComment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//web -- > srv
type Request struct {
	//sessionid
	Sessionid string `protobuf:"bytes,1,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
	//订单id
	OrderId string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	//评论
	Comment              string   `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionid() string {
	if m != nil {
		return m.Sessionid
	}
	return ""
}

func (m *Request) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Request) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

//srv -- web
type Response struct {
	//错误码
	Errno string `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	//错误信息
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.PutComment.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.PutComment.Response")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x3f, 0x4b, 0x04, 0x31,
	0x10, 0xc5, 0x3d, 0xc5, 0xcb, 0xdd, 0x94, 0x83, 0x68, 0xfc, 0x53, 0x9c, 0x5b, 0x59, 0x45, 0xd0,
	0xc6, 0x5e, 0x2c, 0xec, 0x64, 0x6d, 0x45, 0xd1, 0xcb, 0xb0, 0x04, 0x4c, 0x66, 0x9d, 0xc9, 0x8a,
	0x1f, 0x5f, 0x48, 0x22, 0x5b, 0x79, 0x55, 0xf8, 0xbd, 0x17, 0x1e, 0xef, 0x0d, 0x9c, 0x8f, 0xc2,
	0x99, 0xaf, 0xe9, 0xe7, 0x3d, 0x8e, 0x9f, 0xf4, 0xf7, 0xba, 0xa2, 0xe2, 0xc9, 0xc0, 0x2e, 0x86,
	0xad, 0xb0, 0x53, 0xf9, 0x76, 0x4f, 0x53, 0xbe, 0xe7, 0x18, 0x29, 0xe5, 0xee, 0x05, 0x4c, 0x4f,
	0x5f, 0x13, 0x69, 0xc6, 0x0b, 0x58, 0x2b, 0xa9, 0x06, 0x4e, 0xc1, 0xdb, 0xc5, 0x66, 0x71, 0xb5,
	0xee, 0x67, 0x01, 0x4f, 0x61, 0xc5, 0xe2, 0x49, 0xde, 0x82, 0xb7, 0xfb, 0xc5, 0x34, 0x85, 0x1f,
	0x3d, 0x5a, 0x30, 0xdb, 0x1a, 0x67, 0x0f, 0xaa, 0xd3, 0xb0, 0xbb, 0x83, 0x55, 0x4f, 0x3a, 0x72,
	0x52, 0xc2, 0x23, 0x38, 0x24, 0x91, 0xc4, 0x2d, 0xba, 0x02, 0x1e, 0xc3, 0x92, 0x44, 0xa2, 0x0e,
	0x2d, 0xb4, 0xd1, 0xcd, 0x2b, 0x98, 0x87, 0xba, 0x00, 0x9f, 0x01, 0xe6, 0xc2, 0xb8, 0x71, 0xff,
	0x4c, 0x71, 0x6d, 0xc7, 0xd9, 0xe5, 0x8e, 0x1f, 0xb5, 0x4b, 0xb7, 0xf7, 0xb1, 0x2c, 0x77, 0xb9,
	0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x9b, 0x37, 0x82, 0x36, 0x01, 0x00, 0x00,
}
