// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_GetArea

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	//返回错误码
	Errno string `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	//返回错误信息
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	//用自定义的数据类型返回的数组
	Data                 []*ResponseAddress `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetData() []*ResponseAddress {
	if m != nil {
		return m.Data
	}
	return nil
}

//第三个返回值的数据类型结构体
type ResponseAddress struct {
	Aid                  int32    `protobuf:"varint,1,opt,name=aid,proto3" json:"aid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseAddress) Reset()         { *m = ResponseAddress{} }
func (m *ResponseAddress) String() string { return proto.CompactTextString(m) }
func (*ResponseAddress) ProtoMessage()    {}
func (*ResponseAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1, 0}
}

func (m *ResponseAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseAddress.Unmarshal(m, b)
}
func (m *ResponseAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseAddress.Marshal(b, m, deterministic)
}
func (m *ResponseAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseAddress.Merge(m, src)
}
func (m *ResponseAddress) XXX_Size() int {
	return xxx_messageInfo_ResponseAddress.Size(m)
}
func (m *ResponseAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseAddress.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseAddress proto.InternalMessageInfo

func (m *ResponseAddress) GetAid() int32 {
	if m != nil {
		return m.Aid
	}
	return 0
}

func (m *ResponseAddress) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetArea.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetArea.Response")
	proto.RegisterType((*ResponseAddress)(nil), "go.micro.srv.GetArea.Response.address")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4a, 0xc6, 0x30,
	0x14, 0x85, 0xad, 0xfd, 0xff, 0x3f, 0xf6, 0xba, 0xc8, 0xa5, 0x48, 0xa9, 0x28, 0xa5, 0x83, 0x74,
	0x4a, 0xa1, 0x6e, 0x6e, 0x0e, 0x22, 0x38, 0x06, 0x7c, 0x80, 0x68, 0x2e, 0xa5, 0x60, 0x9a, 0x7a,
	0x13, 0xc5, 0x17, 0xf2, 0x3d, 0xc5, 0x34, 0xdd, 0xd4, 0x29, 0xe7, 0x1c, 0xc8, 0xf9, 0x72, 0x02,
	0x17, 0x0b, 0xbb, 0xe0, 0x7a, 0xfa, 0xd4, 0x76, 0x79, 0xa5, 0xed, 0x94, 0x31, 0xc5, 0x72, 0x74,
	0xd2, 0x4e, 0x2f, 0xec, 0xa4, 0xe7, 0x0f, 0xf9, 0x40, 0xe1, 0x8e, 0x49, 0xb7, 0x05, 0x08, 0x45,
	0x6f, 0xef, 0xe4, 0x43, 0xfb, 0x95, 0xc1, 0x89, 0x22, 0xbf, 0xb8, 0xd9, 0x13, 0x96, 0xb0, 0x27,
	0xe6, 0xd9, 0x55, 0x59, 0x93, 0x75, 0x85, 0x5a, 0x0d, 0x9e, 0xc3, 0x81, 0x98, 0xad, 0x1f, 0xab,
	0xe3, 0x18, 0x27, 0x87, 0xb7, 0xb0, 0x33, 0x3a, 0xe8, 0x2a, 0x6f, 0xf2, 0xee, 0x74, 0xb8, 0x96,
	0xbf, 0xa1, 0xe4, 0xd6, 0x2d, 0xb5, 0x31, 0x4c, 0xde, 0xab, 0x78, 0xa7, 0xee, 0x41, 0xa4, 0x00,
	0xcf, 0x20, 0xd7, 0x93, 0x89, 0xc8, 0xbd, 0xfa, 0x91, 0x88, 0xb0, 0x9b, 0xb5, 0xa5, 0x84, 0x8b,
	0x7a, 0x78, 0x02, 0x71, 0xbf, 0x2e, 0xc3, 0x47, 0x10, 0xa9, 0x1d, 0x2f, 0xff, 0x82, 0xc6, 0x71,
	0xf5, 0xd5, 0xff, 0x6f, 0x6a, 0x8f, 0x9e, 0x0f, 0xf1, 0x9b, 0x6e, 0xbe, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x3f, 0x56, 0x73, 0x00, 0x45, 0x01, 0x00, 0x00,
}
