// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_GetUserInfo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//web-->srv
type Request struct {
	//sessionid
	Sessionid            string   `protobuf:"bytes,1,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionid() string {
	if m != nil {
		return m.Sessionid
	}
	return ""
}

//srv--web
type Response struct {
	//错误码
	Errno string `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	//错误信息
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	//用户id
	UserId int64 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	//用户名
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	//手机号
	Mobile string `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	//真实姓名
	RealName string `protobuf:"bytes,6,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	//身份证号
	IdCard string `protobuf:"bytes,7,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	//头衔地址
	AvatarUrl            string   `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Response) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *Response) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *Response) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetUserInfo.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetUserInfo.Response")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x09, 0x6d, 0x93, 0xe6, 0xd8, 0x4e, 0x88, 0x5a, 0x14, 0xa4, 0x92, 0x85, 0x4e, 0x46,
	0x82, 0x9f, 0x80, 0x10, 0xea, 0xc2, 0x10, 0xa9, 0xac, 0x91, 0x5b, 0x1f, 0x95, 0xa5, 0xc4, 0x0e,
	0xe7, 0xa4, 0xe2, 0x77, 0xf2, 0x8b, 0x50, 0xec, 0x20, 0x58, 0x60, 0xb2, 0xdf, 0xf3, 0x7b, 0x27,
	0xf9, 0x3b, 0x58, 0xb6, 0xec, 0x3a, 0x77, 0x47, 0x1f, 0xaa, 0x69, 0x6b, 0xfa, 0x3e, 0x65, 0x70,
	0x51, 0x1c, 0x9c, 0x6c, 0xcc, 0x9e, 0x9d, 0xf4, 0x7c, 0x94, 0xcf, 0xd4, 0x6d, 0x3d, 0xf1, 0xc6,
	0xbe, 0xb9, 0xe2, 0x16, 0xb2, 0x92, 0xde, 0x7b, 0xf2, 0x1d, 0x5e, 0x41, 0xee, 0xc9, 0x7b, 0xe3,
	0xac, 0xd1, 0x22, 0x59, 0x25, 0xeb, 0xbc, 0xfc, 0x31, 0x8a, 0xcf, 0x04, 0xe6, 0x25, 0xf9, 0xd6,
	0x59, 0x4f, 0x78, 0x0e, 0x33, 0x62, 0xb6, 0x6e, 0x8c, 0x45, 0x81, 0x17, 0x90, 0x12, 0x73, 0xe3,
	0x0f, 0xe2, 0x34, 0xd8, 0xa3, 0xc2, 0x05, 0x64, 0xbd, 0x27, 0xae, 0x8c, 0x16, 0x93, 0x55, 0xb2,
	0x9e, 0x94, 0xe9, 0x20, 0x37, 0x1a, 0x11, 0xa6, 0x56, 0x35, 0x24, 0xa6, 0x21, 0x1e, 0xee, 0xc3,
	0x90, 0xc6, 0xed, 0x4c, 0x4d, 0x62, 0x16, 0x87, 0x44, 0x85, 0x4b, 0xc8, 0x99, 0x54, 0x5d, 0x85,
	0x42, 0x1a, 0x9e, 0xe6, 0x83, 0xf1, 0x32, 0x94, 0x16, 0x90, 0x19, 0x5d, 0xed, 0x15, 0x6b, 0x91,
	0xc5, 0x96, 0xd1, 0x8f, 0x8a, 0x35, 0x5e, 0x03, 0xa8, 0xa3, 0xea, 0x14, 0x57, 0x3d, 0xd7, 0x62,
	0x1e, 0x3f, 0x15, 0x9d, 0x2d, 0xd7, 0xf7, 0x0a, 0xb2, 0xa7, 0x08, 0x0a, 0x5f, 0xe1, 0xec, 0x17,
	0x17, 0xbc, 0x91, 0x7f, 0x21, 0x93, 0x23, 0xaf, 0xcb, 0xe2, 0xbf, 0x48, 0x04, 0x55, 0x9c, 0xec,
	0xd2, 0xb0, 0x81, 0x87, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xe6, 0xbc, 0x7c, 0xa0, 0x01,
	0x00, 0x00,
}
